-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.kategoriler
(
    kategoriid integer NOT NULL,
    kategoriad character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT kategoriler_pkey PRIMARY KEY (kategoriid)
);

CREATE TABLE IF NOT EXISTS public.kitaplar
(
    kitapid integer NOT NULL,
    kitapad character varying(50) COLLATE pg_catalog."default",
    stok integer,
    alisfiyat double precision,
    satisfiyat double precision,
    gorsel character varying(100) COLLATE pg_catalog."default",
    kategori integer,
    yazar integer,
    yayinevi integer,
    CONSTRAINT kitaplar_pkey PRIMARY KEY (kitapid)
);

CREATE TABLE IF NOT EXISTS public.yayinevleri
(
    yayineviid integer NOT NULL,
    yayineviad character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT yayinevleri_pkey PRIMARY KEY (yayineviid)
);

CREATE TABLE IF NOT EXISTS public.yazarlar
(
    yazarid integer NOT NULL,
    yazarad character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT yazarlar_pkey PRIMARY KEY (yazarid)
);

ALTER TABLE IF EXISTS public.kitaplar
    ADD CONSTRAINT kitaplar_kategoriler_fk FOREIGN KEY (kitapid)
    REFERENCES public.kategoriler (kategoriid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_kitaplar_yayinevleri_fk
    ON public.kitaplar(kitapid);


ALTER TABLE IF EXISTS public.kitaplar
    ADD CONSTRAINT kitaplar_yayinevleri_fk FOREIGN KEY (kitapid)
    REFERENCES public.yayinevleri (yayineviid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_kitaplar_yayinevleri_fk
    ON public.kitaplar(kitapid);


ALTER TABLE IF EXISTS public.kitaplar
    ADD CONSTRAINT kitaplar_yazarlar_fk FOREIGN KEY (kitapid)
    REFERENCES public.yazarlar (yazarid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_kitaplar_yayinevleri_fk
    ON public.kitaplar(kitapid);

END;